# Copyright 2024 Fujitsu Research of America, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  setup-and-lint:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install dependencies for linting
        run: |
          apt-get update
          python3 -m pip install flake8
      - name: Lint with flake8
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  test:
    needs: setup-and-lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-suite: [test_languagebenchmarks, test_visionbenchmarks]
    container:
      image: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      - name: Install Poetry
        run: |
          apt-get update
          apt-get install -y curl
          curl -sSL https://install.python-poetry.org | python -
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Install Dependencies Using Poetry
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Run ${{ matrix.test-suite }} tests
        run: poetry run pytest test/${{ matrix.test-suite }}.py
